### ISSUE TITLE
4-4與4-5的程式碼import有誤

### ISSUE THREAD

**Issue by Willseed** [iangithub/devllmapp#4]
```py
from langchain.chains import create_retrieval_chain
```

應為

```py
from langchain.chains.retrieval import create_retrieval_chain
```

**Comment by Ko-Ko-Kirk** [comment]
確實該 chain 的路徑是在 retrieval 之下 ，多加個 retrieval ，也是可以跑的，


不過不加，也是可以跑，因為在 __ init __.py 裡已經導出了 create_retrieval_chain 。

https://api.python.langchain.com/en/latest/chains/langchain.chains.retrieval.create_retrieval_chain.html

我們可以看上面官方文件的範例程式碼，也是只使用了 from langchain.chains import create_retrieval_chain
